name: Test NetNoise

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up test environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          traceroute \
          curl \
          jq \
          bc \
          shellcheck

    - name: Test script syntax
      run: |
        echo "Testing BASH syntax..."
        bash -n netnoise.sh
        bash -n install.sh
        bash -n test.sh
        
        echo "Testing module syntax..."
        for module in modules/*.sh; do
          echo "Testing $module..."
          bash -n "$module"
        done

    - name: Run ShellCheck
      run: |
        shellcheck netnoise.sh || true
        shellcheck install.sh || true
        shellcheck test.sh || true
        
        echo "Running ShellCheck on modules..."
        for module in modules/*.sh; do
          echo "Checking $module..."
          shellcheck "$module" || true
        done

    - name: Test configuration loading
      run: |
        echo "Testing configuration file syntax..."
        bash -c "source netnoise.conf && echo 'Configuration loaded successfully'"
        
        echo "Validating configuration variables..."
        bash -c "source netnoise.conf && echo 'Targets: ${#TARGETS[@]}'"
        
        echo "Testing refactored script configuration check..."
        ./netnoise.sh --check

    - name: Test systemd files
      run: |
        echo "Validating systemd service file..."
        systemd-analyze verify netnoise.service || echo "Service file validation completed"
        
        echo "Validating systemd timer file..."
        systemd-analyze verify netnoise.timer || echo "Timer file validation completed"

    - name: Test network connectivity
      run: |
        echo "Testing ping connectivity..."
        ping -c 1 -W 5 google.com || echo "Ping test completed"
        ping -c 1 -W 5 cloudflare.com || echo "Ping test completed"
        
        echo "Testing HTTP connectivity..."
        curl -s -m 10 -o /dev/null https://google.com && echo "HTTP test successful" || echo "HTTP test completed"
        curl -s -m 10 -o /dev/null https://cloudflare.com && echo "HTTP test successful" || echo "HTTP test completed"

    - name: Run test suite
      run: |
        echo "Making test script executable..."
        chmod +x test.sh
        
        echo "Running test suite with verbose output..."
        DEBUG=1 ./test.sh
        exit_code=$?
        
        echo "Test suite completed with exit code: $exit_code"
        if [ $exit_code -ne 0 ]; then
          echo "Test suite failed. Check the output above for details."
          exit $exit_code
        fi

    - name: Test installation script (dry run)
      run: |
        echo "Testing installation script help..."
        bash install.sh help || echo "Help command completed"
        
        echo "Testing installation script syntax..."
        bash -n install.sh

    - name: Test Makefile
      run: |
        echo "Testing Makefile help..."
        make help || echo "Makefile help completed"
        
        echo "Testing Makefile syntax..."
        make -n clean || echo "Makefile syntax check completed"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Lint shell scripts
      run: |
        echo "Running ShellCheck on all shell scripts..."
        shellcheck netnoise.sh || echo "ShellCheck completed for netnoise.sh"
        shellcheck install.sh || echo "ShellCheck completed for install.sh"
        shellcheck test.sh || echo "ShellCheck completed for test.sh"

    - name: Check file permissions
      run: |
        echo "Checking file permissions..."
        ls -la *.sh
        echo "All shell scripts should be executable"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up security tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bandit

    - name: Security scan
      run: |
        echo "Running security checks..."
        echo "Checking for hardcoded secrets..."
        grep -r "password\|secret\|key" . --exclude-dir=.git || echo "No hardcoded secrets found"
        
        echo "Checking for sudo usage..."
        grep -r "sudo" . --exclude-dir=.git || echo "Sudo usage found (expected for systemd)"

    - name: Validate systemd security
      run: |
        echo "Checking systemd service security settings..."
        grep -A 10 "Security settings" netnoise.service || echo "Security settings found"

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check documentation
      run: |
        echo "Checking README.md exists and has content..."
        test -f README.md && echo "README.md found"
        wc -l README.md
        
        echo "Checking for required sections..."
        grep -q "# NetNoise" README.md && echo "Title found"
        grep -q "## Features" README.md && echo "Features section found"
        grep -q "## Installation" README.md && echo "Installation section found"
        grep -q "## Configuration" README.md && echo "Configuration section found"

    - name: Validate links
      run: |
        echo "Checking for broken internal links..."
        grep -o '\[.*\](.*)' README.md | grep -v 'http' || echo "Internal links checked"

  build-test:
    runs-on: ubuntu-latest
    needs: [test, lint, security, documentation]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Simulate installation
      run: |
        echo "Testing installation process..."
        mkdir -p /tmp/test-install
        cp netnoise.sh /tmp/test-install/
        cp netnoise.conf /tmp/test-install/
        cp netnoise.service /tmp/test-install/
        cp netnoise.timer /tmp/test-install/
        echo "Installation simulation completed"

    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        test -f netnoise.sh && echo "✓ netnoise.sh"
        test -f netnoise.conf && echo "✓ netnoise.conf"
        test -f netnoise.service && echo "✓ netnoise.service"
        test -f netnoise.timer && echo "✓ netnoise.timer"
        test -f install.sh && echo "✓ install.sh"
        test -f test.sh && echo "✓ test.sh"
        test -f Makefile && echo "✓ Makefile"
        test -f README.md && echo "✓ README.md"
        
        echo "Checking modular structure..."
        test -d modules && echo "✓ modules directory"
        for module in modules/*.sh; do
          test -f "$module" && echo "✓ $(basename "$module")"
        done
